package de.hhn.aib.swlab.ex3.server.singlebackend.game;

import de.hhn.aib.swlab.ex3.server.singlebackend.external.model.Message;
import de.hhn.aib.swlab.ex3.server.singlebackend.external.model.Player;

import javax.validation.constraints.NotNull;

// TODO add documentation
public interface MyGameBackend {

    /**
     * This method is invoked when the game backend is created. The creation is requested by the external management system.
     * You can assert that no player is in the game by the invocation. You should implement this method to initialize variables,
     * e.g. to generate a random game world.
     * You should *not* invoke this method manually.
     */
    void onInit();

    /**
     * This method is invoked when a player joins the game. This method can be used to initialize player specific details
     * and/or send him the initial data (e.g. generated by the {@link #onInit()} method.
     * You can assume that the player is authenticated and assigned to this game.
     *
     * @param player the player who joins the game. This parameter is never null when the method is invoked externally.
     *               You can assume that the name and player-index are not null
     */
    boolean onPlayerJoined(@NotNull Player player);

    /**
     * This method is invoked when a player leaves the game. This method can be used to quit the game and publish the score
     * or just send the information to the other players and continue the game.
     * @param player the player who leaves the game. This parameter is never null when the method is invoked externally.
     *               You can assume that the name and player-index are not null
     */
    void onPlayerLeft(@NotNull Player player);
    // TODO add documentation
    void onMessageFromPlayer(@NotNull Message message);
    // TODO add documentation
    void onPing();

    // implemented by the AbstractGameBackend

    // TODO add documentation
    void sendMessageToPlayer(@NotNull String message, Player player);

    // TODO add documentation
    void quitGame(String gameID);

    // TODO add documentation
    void publishScore(Player player, int score);
}
